package aic.gas.sc.gg_bot.abstract_bot.model.bot;

import aic.gas.sc.gg_bot.abstract_bot.model.features.FeatureContainerHeader;
import java.util.Collections;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Enumeration of all feature container headers as static classes
 */
public class FeatureContainerHeaders {

  //ECO manager
  public static final FeatureContainerHeader BUILDING_EXTRACTOR = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefs(Collections.singleton(
          FactConverters.COUNT_OF_WORKERS))
      .convertersForFactsForGlobalBeliefsByAgentType(
          Collections.singleton(FactConverters.COUNT_OF_BASES))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();
  public static final FeatureContainerHeader INCREASING_CAPACITY = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();
  public static final FeatureContainerHeader TRAINING_WORKER = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefs(Collections.singleton(FactConverters.COUNT_OF_WORKERS))
      .convertersForFactsForGlobalBeliefsByAgentType(
          Stream.of(FactConverters.COUNT_OF_BASES, FactConverters.GAME_PHASE)
              .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader EXPANDING = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefs(Collections.singleton(FactConverters.COUNT_OF_WORKERS))
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  //Build order manager
  public static final FeatureContainerHeader BUILDING_POOL = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefs(Collections.singleton(FactConverters.COUNT_OF_WORKERS))
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader UPGRADING_TO_LAIR = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader BUILDING_SPIRE = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader BUILDING_HYDRALISK_DEN = FeatureContainerHeader
      .builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader BUILDING_EVOLUTION_CHAMBER = FeatureContainerHeader
      .builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.COUNT_OF_EXTRACTORS,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  //Unit order manager
  public static final FeatureContainerHeader BOOSTING_AIR = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader BOOSTING_GROUND_MELEE = FeatureContainerHeader
      .builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader BOOSTING_GROUND_RANGED = FeatureContainerHeader
      .builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.CURRENT_POPULATION,
          FactConverters.MAX_POPULATION,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.AVERAGE_COUNT_OF_WORKERS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_MINERALS_PER_BASE,
          FactConverters.AVERAGE_COUNT_OF_WORKERS_MINING_GAS_PER_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .build();

  //BASE
  public static final FeatureContainerHeader HOLDING = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .convertersForFactSets(Stream.of(
          FactConverters.SUM_OF_ENEMY_AIR_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_HP_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_HP_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_OWN_AIR_DMG_BASE,
          FactConverters.SUM_OF_OWN_GROUND_DMG_BASE,
          FactConverters.SUM_OF_OWN_AIR_HP_BASE,
          FactConverters.SUM_OF_OWN_GROUND_HP_BASE,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG_BASE,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG_BASE,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS_BASE,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_OWN_AIR_UNITS_BASE,
          FactConverters.SUM_OF_OWN_GROUND_UNITS_BASE)
          .collect(Collectors.toSet()))
      .convertersForFacts(Stream.of(
          FactConverters.IS_BASE,
          FactConverters.IS_ENEMY_BASE,
          FactConverters.IS_MINERAL_ONLY,
          FactConverters.IS_ISLAND,
          FactConverters.IS_START_LOCATION)
          .collect(Collectors.toSet()))
      .build();

  public static final FeatureContainerHeader DEFENSE = FeatureContainerHeader.builder()
      .convertersForFactsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.COUNT_OF_BASES,
          FactConverters.COUNT_OF_ENEMY_BASES,
          FactConverters.AVAILABLE_BASES,
          FactConverters.GAME_PHASE)
          .collect(Collectors.toSet()))
      .convertersForFactSetsForGlobalBeliefsByAgentType(Stream.of(
          FactConverters.SUM_OF_ENEMY_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_AIR_HP,
          FactConverters.SUM_OF_ENEMY_GROUND_HP,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_DMG,
          FactConverters.SUM_OF_OWN_GROUND_DMG,
          FactConverters.SUM_OF_OWN_AIR_HP,
          FactConverters.SUM_OF_OWN_GROUND_HP,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS,
          FactConverters.SUM_OF_OWN_AIR_UNITS,
          FactConverters.SUM_OF_OWN_GROUND_UNITS)
          .collect(Collectors.toSet()))
      .convertersForFactSets(Stream.of(
          FactConverters.SUM_OF_ENEMY_AIR_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_HP_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_HP_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_SHIELDS_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_SHIELDS_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_DMG_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_AIR_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_STATIC_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_AIR_UNITS_BASE,
          FactConverters.SUM_OF_ENEMY_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_OWN_AIR_DMG_BASE,
          FactConverters.SUM_OF_OWN_GROUND_DMG_BASE,
          FactConverters.SUM_OF_OWN_AIR_HP_BASE,
          FactConverters.SUM_OF_OWN_GROUND_HP_BASE,
          FactConverters.SUM_OF_OWN_STATIC_AIR_DMG_BASE,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_DMG_BASE,
          FactConverters.SUM_OF_OWN_STATIC_AIR_UNITS_BASE,
          FactConverters.SUM_OF_OWN_STATIC_GROUND_UNITS_BASE,
          FactConverters.SUM_OF_OWN_AIR_UNITS_BASE,
          FactConverters.SUM_OF_OWN_GROUND_UNITS_BASE,
          FactConverters.COUNT_OF_CREEP_COLONIES_AT_BASE,
          FactConverters.COUNT_OF_SPORE_COLONIES_AT_BASE,
          FactConverters.COUNT_OF_SUNKEN_COLONIES_AT_BASE)
          .collect(Collectors.toSet()))
      .convertersForFacts(Stream.of(
          FactConverters.IS_BASE,
          FactConverters.IS_ENEMY_BASE,
          FactConverters.IS_MINERAL_ONLY,
          FactConverters.IS_ISLAND,
          FactConverters.IS_START_LOCATION)
          .collect(Collectors.toSet()))
      .build();

}
