spring:
  application:
    name: Replay Parser

  datasource:
    url: jdbc:postgresql://localhost:5432/sc-parser
    username: postgres
    password: heslo
    driver-class-name:  org.postgresql.Driver
    test-while-idle:  true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    format_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: ru.megadevelopers.hibernate.dialect.SequencePerTablePostgresDialect

paths-to-replays:
  replays-path: 'C:\Program Files (x86)\StarCraft\Maps\Replays'
  bots: bots
  players: players

chaosluncher-configuration:
  path: 'C:\Users\Jan\Desktop\Chaosluncher Run With Full Privileges.lnk'